// <auto-generated />
using CareerMap.Recommendations.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CareerMap.Recommendations.Infrastructure.Migrations
{
    [DbContext(typeof(RecommendationsDbContext))]
    partial class RecommendationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CareerMap.Recommendations.Domain.Entities.Carreira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompetenciasNecessarias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Carreiras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = "Tecnologia",
                            CompetenciasNecessarias = "[{\"Id\":1,\"Nome\":\"C#\",\"Tipo\":\"Hard Skill\"},{\"Id\":2,\"Nome\":\".NET Core\",\"Tipo\":\"Hard Skill\"},{\"Id\":3,\"Nome\":\"SQL\",\"Tipo\":\"Hard Skill\"}]",
                            Descricao = "Foco em APIs RESTful com .NET e Entity Framework.",
                            Nivel = 1,
                            Nome = "Desenvolvedor Backend .NET Júnior"
                        });
                });

            modelBuilder.Entity("CareerMap.Recommendations.Domain.Entities.Competencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Competencias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "C#",
                            Tipo = "Hard Skill"
                        },
                        new
                        {
                            Id = 2,
                            Nome = ".NET Core",
                            Tipo = "Hard Skill"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "SQL",
                            Tipo = "Hard Skill"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Comunicação",
                            Tipo = "Soft Skill"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Resolução de Problemas",
                            Tipo = "Soft Skill"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
